name: Bicep Resources CI

on:
    push:
        branches:
            - 'feature/**' # Branches containing 'feature' in the name
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Update Packages and Install Bicep CLI
          run: | 
            sudo apt-get update && \
            sudo az bicep upgrade
        
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Bicep files
          run: |
            for file in $(find ./src -name '*.bicep'); do
                echo "Building $file"
                az bicep build --file $file --outdir ./bicepArtifacts
            done
        
        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: bicepFiles
            path: ./bicepArtifacts/*.json
    
    publish-bicep-artifacts:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download Bicep Artifacts
          uses: actions/download-artifact@v4
          with:
            name: bicepFiles

        - name: Upload Bicep Artifacts to Storage
          run: |
            # Add your upload logic here, e.g., az storage blob upload
            echo "Uploading Bicep artifacts"