name: Bicep Resources Continuous Deployment

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: write # Grants write access to repository content, including creating releases.

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Update Packages and Install Bicep CLI
          run: | 
            sudo apt-get update && \
            sudo az bicep upgrade
        
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Bicep files
          run: |
            for file in $(find ./src -name '*.bicep'); do
                echo "Building $file"
                az bicep build --file $file --outdir ./bicepArtifacts
            done
        
        - name: Compress Bicep Artifacts
          run: |
            zip -r bicepArtifacts.zip ./bicepArtifacts

        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: bicepArtifacts.zip
            path: bicepArtifacts.zip # Reference the .zip file, not the directory
    
    publish-bicep-artifacts:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download Bicep Artifacts
          uses: actions/download-artifact@v4
          with:
            name: bicepArtifacts.zip
            path: bicepArtifacts.zip # Again, use the .zip file

        - name: Upload Bicep Artifacts to Storage
          run: |
            # Add your upload logic here, e.g., az storage blob upload
            echo "Uploading Bicep artifacts"

    create-release:
        runs-on: ubuntu-latest
        needs: publish-bicep-artifacts
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download Bicep Artifacts
          uses: actions/download-artifact@v4
          with:
            name: bicepArtifacts.zip
            path: bicepArtifacts.zip

        - name: Create GitHub Release
          id: create_release
          uses: actions/create-release@v1
          with:
            tag_name: v1.0.${{github.run_number}} # Automatically increment tag number
            release_name: Release v1.0.${{github.run_number}} # Automatically increment release name
            body: |
              Pull Request Info: ${{ github.event.pull_request.html_url }}
              Commits: ${{ toJson(github.event.commits) }}
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: bicepArtifacts.zip # Reference the .zip file
            asset_name: bicepArtifacts.zip
            asset_content_type: application/zip
