name: Bicep Resources Continuous Integration

on:
    workflow_dispatch: # Allows manual triggering of the workflow
    push:
        branches:
            - 'feature/**' # Branches containing 'feature' in the name
            - 'bugfix/**' # Branches containing 'bugfix' in the name
    pull_request:
        branches:
            - main
            
permissions:
    contents: write # Grants write access to repository content, including creating releases.

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Update Packages and Install Bicep CLI
          run: | 
            sudo apt-get update && \
            sudo az bicep upgrade
        
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Bicep files
          run: |
            for file in $(find ./src -name '*.bicep'); do
              folder=$(dirname "$file" | sed 's|./src/||')
              echo "Building $file in folder $folder"
              mkdir ./bicepArtifacts/$folder
              az bicep build --file "$file" --outdir "./bicepArtifacts/$folder"
            done
            for file in $(find ./src -name '*.bicepparam'); do
                folder=$(dirname "$file" | sed 's|./src/||')
                echo "Building $file in folder $folder"
                mkdir ./bicepArtifacts/$folder
                az bicep build-params --file $file --outdir "./bicepArtifacts/$folder"
            done
        - name: Compress Bicep Artifacts
          run: |
            zip -r bicepArtifacts_v1.0.${{ github.run_number }}.zip ./bicepArtifacts

        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: bicepArtifacts_v1.0.${{ github.run_number }}.zip
            path: bicepArtifacts_v1.0.${{ github.run_number }}.zip
