name: Bicep Resources CI

on:
    push:
        branches:
            - '**' # All branches
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Update Packages and Install Bicep CLI
          run: | 
            sudo apt-get update && \
            sudo apt-get upgrade -y && \
            sudo az bicep upgrade
        
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Bicep files
          run: |
            for file in $(find ./src -name '*.bicep'); do
                echo "Building $file"
                az bicep build --file $file --outdir ./bicepArtifacts
            done

        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: artifactsBicep-ARM-Templates
            path: ./bicepArtifacts/*.json