name: Bicep Resources CI

on:
    push:
        branches:
            - 'feature/**' # Branches containing 'feature' in the name
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Update Packages and Install Bicep CLI
          run: | 
            sudo apt-get update && \
            sudo az bicep upgrade
        
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Bicep files
          run: |
            for file in $(find ./src -name '*.bicep'); do
                echo "Building $file"
                az bicep build --file $file --outdir ./bicepArtifacts
            done
        - name: Outuput Bicep files
          uses: actions/Outuput@v2
          with:
            name: bicepFiles
            value: ./bicepArtifacts/*.json
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: artifactsBicep-ARM-Templates
            path: ./bicepArtifacts/*.json