name: Bicep Resources Continuous Deployment

on:
    workflow_dispatch: # Allows manual triggering of the workflow
    merge_group: # Triggers the workflow when a merge group is completed
        types: checks_requested

permissions:
    contents: write # Grants write access to repository content, including creating releases.

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Update Packages and Install Bicep CLI
          run: | 
            sudo apt-get update && \
            sudo apt-get upgrade -y && \
            sudo az bicep upgrade
        
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Bicep files
          run: |
            for file in $(find ./src -name '*.bicep'); do
                echo "Building $file"
                az bicep build --file $file --outdir ./bicepArtifacts
            done
        
        - name: Compress Bicep Artifacts
          run: |
            zip -r bicepArtifacts_v1.0.${{ github.run_number }}.zip ./bicepArtifacts

        - name: Upload Bicep Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: bicepArtifacts_v1.0.${{ github.run_number }}.zip
            path: bicepArtifacts_v1.0.${{ github.run_number }}.zip
    
    publish-bicep-artifacts:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download Bicep Artifacts
          uses: actions/download-artifact@v4
          with:
            name: bicepArtifacts_v1.0.${{ github.run_number }}.zip

        - name: Upload Bicep Artifacts to Storage
          run: |
            # Add your upload logic here
            echo "Uploading Bicep artifacts"

    create-release:
        runs-on: ubuntu-latest
        needs: publish-bicep-artifacts
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Download Bicep Artifacts
          uses: actions/download-artifact@v4
          with:
            name: bicepArtifacts_v1.0.${{ github.run_number }}.zip

        - name: Create GitHub Release
          id: create_release
          uses: actions/create-release@v1
          with:
            tag_name: v1.0.${{ github.run_number }}
            release_name: Release v1.0.${{ github.run_number }}
            body: |
              Pull Request Info: ${{ github.event.pull_request.html_url }}
              Commits: ${{ toJson(github.event.commits) }}
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: bicepArtifacts_v1.0.${{ github.run_number }}.zip
            asset_name: bicepArtifacts_v1.0.${{ github.run_number }}.zip
            asset_content_type: application/zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

